```{r}

```




```{r}
Duplicator = 
#' Duplicator base class
#' 
#' Object interface which supports deep copying (or something close to it). Implements the 'duplicate' method, which returns a deep copy of the calling object instance.
#' 
#' Duplicates are created by creating a new instance of the calling object and populating all fields with the fields of the calling object. If a field on the calling instance is a complex object (i.e. not a basic type, e.g. numeric, character, etc), then the complex object must also be a Duplicator object (or child class). If not, the duplicated object will contain a reference to the field of the original object, not a true copy. 
#' 
#' @field parent_class character. 
#' @field new_field numeric. 
#'
#' @return
#' @export
#'
#' @examples
Dulicator = 
  setRefClass(
    "Duplicator",
    methods = 
      list(
        duplicate = 
          function(.self) {
            dup__ = methods::new(Class = .self$getClass())
            dup__$import(.self)
            return(dup__)
          }
      )
  )

Builder = 
  setRefClass( 
    "Builder",
    contains = "Duplicator",
    fields = 
      list(
        product_class = "character"
      ),
    methods = 
      list(
        get_refclass_fields = 
          function(rc) {
            return(
              getRefClass(rc)$fields()
            )
          },
        
        set_field = 
          function(f, v) {
            dup__ = .self$duplicate()
            dup__[[f]] = v
            
            return(dup__)
          },
        
        subset_fields = 
          function(product_class) {
            # Get the names of the fields in the product class
            # By definition, all of these fields should also be present in this class
            product_class_field_names = 
              names(get_refclass_fields(product_class))
            
            fields__ = list()
            for(f_ in product_class_field_names) {
              fields__[[f_]] = .self[[f_]]
            }
            return(fields__)
          }
      )
  )

ClassBuilder_Builder = 
#' Builder object for reference-class generators of builder objects 
#'
#' This class facilitates building generators for other reference classes that follow the builder pattern, and automatically populates the new object with getter/setter methods. All generators produced by this object will build objects that are children of the `Builder` class.
#'
#' @field class_name Name for new class 
#' @field contains contains
#' @field fields list. 
#' @field methods list. 
#'
#' @return
#' @export
#'
#' @examples
  setRefClass(
    "ClassBuilder_Builder",
    contains = "Builder",
    fields = 
      list(
        class_name = "character",
        product_class = "character"
      ),
    methods = 
      list(
        make_get_methods = 
          function(product_class_field_names) {
            # Build methods as a named list of functions
            args_ = list()
            for (f_ in product_class_field_names) {
              args_[[paste0("get_", f_)]] = 
                eval(
                  parse(
                    text = 
                      paste0("function(v) {return(", f_, ")}")
                  )
                )
            }
            
            return(args_)
          },
        
        make_set_methods = 
          function(product_class_field_names) {
            # Build methods as a named list of functions
            args_ = list()
            for (f_ in product_class_field_names) {
              args_[[paste0("set_", f_)]] = 
                eval(
                  parse(
                    text = 
                      # paste0("function(v) {", f_, " <<- v}")
                      paste0("function(v) {set_field('", f_, "', v)}")
                  )
                )
            }
            
            return(args_)
          },
        
        make_build_method = 
          function(pc) {
            args = list()
            
            args[['build']] = 
              eval(
                parse(
                  text =
                    paste0(
                      "function() {do.call(what=methods::new, args = c('Class' = '", 
                      pc, 
                      "', subset_fields('", 
                      pc, 
                      "')))}"
                    )
                )
              )
            
            return(args)
          },
        
        build = 
          function() {
            product_class_field_defs = get_refclass_fields(product_class)
            product_class_field_names = names(product_class_field_defs)
            
            cg = 
              setRefClass(
                class_name,
                contains = "Builder",
                fields = product_class_field_defs
              )
            
            # Construct builder object methods
            args = list()
            # Define getter/setter functions
            args = append(args, make_get_methods(product_class_field_names))
            args = append(args, make_set_methods(product_class_field_names))
            # Make build function
            args = append(args, make_build_method(product_class))
            # Attach methods to reference class generator
            do.call(cg$methods, args = args)
            
            # Return constructed generator
            return(cg)
          }
      )
  )


# Define a Builder class for Decoders
Decoder_Builder = 
  ClassBuilder_Builder(
    class_name = "Decoder_Builder",
    product_class = "Decoder"
  )$build()
```

```{r}
Decoder_Lotek_1000.1100.1250_Builder = 
  # Start with base class builder
  Decoder_Builder()$
  # Add specifics
  set_identifier(Identifier_Lotek_1000.1100.1250())$
  set_metadata_map(DataMap_Lotek_1000.1100.1250_TagMetaData())$
  set_data_maps(list(DataMap_Lotek_1000.1100.1250_InstantSensorData()))
```

```{r}
make_build_method = 
  function(pc) {
    args = list()
    
    args[['build']] = 
      eval(
        parse(
          text =
            paste0(
              "function() {do.call(what=methods::new, args = c('Class' = '", 
              pc, 
              "', fields__))}"
            )
        )
      )
    
    return(args)
  }
```


















































