```{r}
# Build the DecoderTree from the Decoder_MasterList

DecoderTree = 
  data.frame()

for(dc in Decoder_MasterList) {
  DecoderTree = 
    rbind(
      DecoderTree,
      data.frame(
        make = dc()$metadata_map$make,
        model = dc()$metadata_map$model,
        class = class(dc())[[1]]
      )
    )
}

Filt
```


```{r}
data_d = here::here('data')
lt_d = file.path(data_d, 'Lotek')
mt_d = file.path(data_d, 'Microwave Telemetry')

lotek_1000.1100.1250_d = file.path(lt_d, "LTD 1300-LTD 1000-LTD 1110-LTD 1250", "Sablefish", "3315")
lotek_1300_d = file.path(lt_d, "LTD 1300-LTD 1000-LTD 1110-LTD 1250", "Sablefish", "5712")
lotek_1400.1800_d = file.path(lt_d, "LAT 1400-LAT 1800", "Sablefish", "0507")
mt_xtag_d = file.path(mt_d, "X-Tag", "Lingcod", "128306")


d = mt_xtag_d


# Find any decoders in the Decoder_MasterList whose Identifier objects positively match the directory in question
Filter(
  function(dc) {dc()$identifier$identify(d)},
  Decoder_MasterList
)
```

```{r}
#' Maps raw tag data to the appropriate Decoder based on structure of the raw data
#' 
#' Makes decisions based on some pretty nitty-gritty details, like naming 
#' conventions, file-types present, number of files present, etc. As such, it's 
#' crucial that the data has not been altered by the user in any way since being 
#' extracted from the tag and/or run through any post-processing software.
#'
#' @field master_list__ list. The list of all Decoders from which to choose. 
#' Internal reference field, not intended to be set by user. Any value passed 
#' to this field will be overwritten on construction
TagIdentifier = 
  setRefClass(
    "TagIdentifier",
    fields = 
      list(
        master_list__ = "list"
      ),
    methods = 
      list(
        initialize = 
          function(...) {
            callSuper(...)
            # Set the master list
            master_list__ <<- Decoder_MasterList
          },
        
        identify_tag_decoder = 
          function(d) {
            # Find any decoders in the Decoder_MasterList whose Identifier objects positively match the directory in question
            matching_decoders = 
              Filter(
                function(dc) {dc()$identifier$identify(d)},
                .self$master_list__
              )
            
            if (length(matching_decoders) == 1) {
              return(matching_decoders[[1]](d = d))
            }
          }
      )
  )

TagIdentifier()$identify_tag_decoder(mt_xtag_d)$decode(con)

```






















