
Notebook to help determine likely units of pressure by calculating the apparent depth in seawater assuming different SI units for the value 
```{r}
# Constants
rho_ = units::set_units(1000, 'kg/m^3') # Density of water
g_ = units::set_units(9.8, 'm/s^2') # Gravitational constant
p_0_ = units::set_units(1, 'atm') # Pressure at sea level

pressure_at_depth = 
  function(d, u_ = "psi") {
    units::set_units(
      p_0_ + d * rho_ * g_,
      u_, 
      mode = 'standard'
    )
  }

# Calculate the depth of a data point based on the pressure reading
# Pressure value must have units specified
depth_from_pressure = 
  function(p) {
    units::set_units(
      (p - p_0_)/(rho_ * g_),
      "m"
    )
  }


calc_depth_for_pressure_across_units = 
  function(
    pressure,
    units__ = 
      c(
        'psi', 
        'Pa',
        'MPa',
        'bar',
        'decibar',
        'mmhg'
      )
  ) {
    units__ %>% 
    purrr::reduce(
      .init = 
        data.frame(
          pressure = units::drop_units(pressure)
        ),
      .f = 
        function(df, u_) {
          df %>% 
          dplyr::mutate(
            "{u_}" := 
              depth_from_pressure(
                units::set_units(pressure, u_, mode="standard")
              )
            
          )
        }
    )
  }

plot_depth_dist_by_pressure_unit = 
  function(
    press_units_df__,
    benchmarks = NULL,
    exclude = c()
  ) {
    p = 
      press_units_df__ %>% 
      tidyr::pivot_longer(
        ., 
        cols = names(.)[names(.) != 'pressure'],
        names_to = 'unit', values_to = 'depth'
      ) %>% 
      dplyr::filter(
        !unit %in% exclude
      ) %>% 
      ggplot2::ggplot() + 
      ggplot2::geom_histogram(aes(depth, fill = unit), position='dodge')
    
    if(!is.null(benchmarks)) {
      # Convert list to dataframe
      benchmarks = 
        benchmarks %>% 
        data.frame() %>% 
        tidyr::pivot_longer(., cols = names(.), names_to = "name", values_to = "x") %>% 
        dplyr::mutate(x = units::set_units(x, 'm'))
      
      # Add depth benchmark indicators
      p = 
        p + 
        ggplot2::geom_segment(
          data = benchmarks,
          aes(
            x = x, 
            xend = x, 
            y=0, 
            yend=nrow(press_units_df__)
          ),
          size = 2,
          linetype = "dashed",
        ) + 
        ggplot2::geom_label(
          data = benchmarks, 
          aes(
            x = x, 
            y = nrow(press_units_df__)*1.1, 
            label = name
          )
        )
    }
    
    return(p)
  }



labeled_depths = 
  list(
    "sealevel" = 0,
    "shelf" = 200,
    "basin" = 3500
  )
```


Plot
```{r}
calc_depth_for_pressure_across_units(
  dat_t_$pressure
) %>% 
  plot_depth_dist_by_pressure_unit(
    exclude = c("Pa", "MPa", "bar", "mmhg")
    # benchmarks = 
    #   list(
    #     "sealevel" = 0,
    #     "shelf" = 200
    #     # "basin" = 3500
    #   )
  )
```


Calibration of depth function
1000m of depth in seawater should equal ~1464.5 psi of pressure
```{r}
rho_ = units::set_units(10^3, "kg/m^3")
g_ = units::set_units(9.80, "m/s^2")

depth_ = units::set_units(1000, m)

p_0_ = units::set_units(1, 'atm')

p = 
  units::set_units(
    # Weight of the water above
    depth_ * g_ * rho_ + 
    # Weight of the atmosphere above the water
    p_0_, 
    'psi')

# (p - p_0_)/(rho_ * g_)


# Calculate the depth of a data point based on the pressure reading
# Pressure value must have units specified
depth_from_pressure = 
  function(p) {
    units::set_units(
      (p - p_0_)/(rho_ * g_),
      "m"
    )
  }
```
```{r}
depth_from_pressure(
  p = units::set_units(13, 'decibar')
)


pressure_at_depth(
  units::set_units(0, 'm'),
  u_ = "decibar"
)
```

















