```{r}
library(tidyverse)

data_d = here::here('data')
lt_d = file.path(data_d, 'Lotek')
mt_d = file.path(data_d, 'Microwave Telemetry')
so_d = file.path(data_d, 'Star Oddi')
wc_d = file.path(data_d, 'Wildlife Computers')

lotek_1000.1100.1250_d = file.path(lt_d, "LTD 1300-LTD 1000-LTD 1110-LTD 1250", "Sablefish", "3315")
lotek_1300_d = file.path(lt_d, "LTD 1300-LTD 1000-LTD 1110-LTD 1250", "Sablefish", "5712")
lotek_1400.1800_d = file.path(lt_d, "LAT 1400-LAT 1800", "Sablefish", "0507")
mt_xtag_d = file.path(mt_d, "X-Tag", "Lingcod", "128306")
so_dst_d = file.path(so_d, "DST" , "Sablefish", "JS7977")
so_dst_m_d = file.path(so_d, "DST magnetic" , "Sablefish", "JS927")
so_dst_mf_d = file.path(so_d, "DST milli-F" , "Sablefish", "JS122")
```

```{r}
Identifier_StarOddi_DST = 
  setRefClass(
    "Identifier_StarOddi_DST",
    contains = "Identifier",
    methods = 
      list(
        
        # The only way I know of to distinguish between the DST and DST milli-F 
        # tags is by looking at the format of this one column in the datasheet.
        # It's brittle, but it's the best we've got.
        check_xy_sheet_datetime_column_format = 
          function(d) {
            fp =
              list.files(
                d, 
                full.names = T, 
                pattern = "^JS\\d+\\.xlsx"
              )
            
            suppressMessages(
              {
                dat = readxl::read_xlsx(fp, sheet = "XY", n_max = 10)
              }
            )
            
            # DST
            return(
              all(
                "POSIXct" %in% class(dat[[1]]),
                "POSIXt" %in% class(dat[[1]])
              )
            )
          },
        
        identify = 
          function(d) {
            return(
              all(
                .self$check_for_files(d, "^JS\\d+\\.xlsx"),
                # Check that all files in the directory are either the datafile, or Excel's temporary lock file
                .self$check_for_files(d, "(~$)*JS\\d+\\.xlsx", n=length(list.files(d))),
                .self$check_xy_sheet_datetime_column_format(d)
              )
            )
          }
      )
  )

Identifier_StarOddi_DST()$identify(so_dst_d)
Identifier_StarOddi_DST()$identify(so_dst_mf_d)
Identifier_StarOddi_DST()$identify(so_dst_m_d)
```

```{r}
Identifier_StarOddi_DSTmilliF = 
  setRefClass(
    "Identifier_StarOddi_DSTmilliF",
    contains = "Identifier",
    methods = 
      list(
        
        # The only way I know of to distinguish between the DST and DST milli-F 
        # tags is by looking at the format of this one column in the datasheet.
        # It's brittle, but it's the best we've got.
        check_xy_sheet_datetime_column_format = 
          function(d) {
            fp =
              list.files(
                d, 
                full.names = T, 
                pattern = "^JS\\d+\\.xlsx"
              )
            
            suppressMessages(
              {
                dat = readxl::read_xlsx(fp, sheet = "XY", n_max = 10)
              }
            )
            
            # DST
            return(class(dat[[1]]) == "numeric")
          },
        
        check_fields =
          function(d) {
            dat = 
              readxl::read_xlsx(
                list.files(
                  d, 
                  pattern = "^JS\\d+\\.xlsx",
                  full.names = T
                ),
                sheet = "DAT",
                n_max = 10
              )
            
            dat_f = names(dat)
            
            return(
              all(
                # Check the number of fields
                length(dat_f) == 3,
                # Check that the necessary fields are present
                !"Comp.Head(째)" %in% dat_f,
                !"Tilt-X(째)" %in% dat_f
              )
            )
            
          },
        
        identify = 
          function(d) {
            return(
              all(
                .self$check_for_files(d, "^JS\\d+\\.xlsx"),
                # Check that all files in the directory are either the datafile, or Excel's temporary lock file
                .self$check_for_files(d, "(~$)*JS\\d+\\.xlsx", n=length(list.files(d))),
                .self$check_xy_sheet_datetime_column_format(d),
                .self$check_fields(d)
              )
            )
          }
      )
  )

Identifier_StarOddi_DSTmilliF()$identify(so_dst_mf_d)
Identifier_StarOddi_DSTmilliF()$identify(so_dst_d)
Identifier_StarOddi_DSTmilliF()$identify(so_dst_m_d)
```





```{r}
Identifier_StarOddi_DSTmagnetic = 
  setRefClass(
    "Identifier_StarOddi_DSTmagnetic",
    contains = "Identifier",
    methods = 
      list(
        check_fields =
          function(d) {
            dat = 
              readxl::read_xlsx(
                list.files(
                  d, 
                  pattern = "^JS\\d+\\.xlsx",
                  full.names = T
                ),
                sheet = "DAT",
                n_max = 10
              )
            
            dat_f = names(dat)
            
            return(
              all(
                # Check the number of fields
                length(dat_f) == 11,
                # Check that the necessary fields are present
                "Comp.Head(째)" %in% dat_f,
                "Tilt-X(째)" %in% dat_f
              )
            )
            
          },
        
        identify = 
          function(d) {
            return(
              all(
                .self$check_for_files(d, "^JS\\d+\\.xlsx"),
                # Check that all files in the directory are either the datafile, or Excel's temporary lock file
                .self$check_for_files(d, "(~$)*JS\\d+\\.xlsx", n=length(list.files(d))),
                .self$check_fields(d)
              )
            )
          }
      )
  )

Identifier_StarOddi_DSTmagnetic()$identify(so_dst_m_d)
Identifier_StarOddi_DSTmagnetic()$identify(so_dst_mf_d)
Identifier_StarOddi_DSTmagnetic()$identify(so_dst_d)
```




































