```{r}
library(tidyverse)
```

Scratch
```{r}
data_root = here::here('data')
lotek_data = file.path(data_root, 'Lotek')

template_tag_d_ltd_1000_1100_1250 = file.path(lotek_data, 'LTD 1300-LTD 1000-LTD 1110-LTD 1250', 'Sablefish', '3315')

template_tag_d_lat_1300 = file.path(lotek_data, 'LTD 1300-LTD 1000-LTD 1110-LTD 1250', 'Sablefish', '5712')

template_tag_fp_lat_1400_d = file.path(lotek_data, 'LAT 1400-LAT 1800', 'Sablefish', '1535')
template_tag_fp_lat_1400_fp = file.path(template_tag_fp_lat_1400_d, 'LAT140_1535_180907_110343_00.csv')

template_tag_fp_lat_1800_d = file.path(lotek_data, 'LAT 1400-LAT 1800', 'Sablefish', '0507')
template_tag_fp_lat_1800_fp = file.path(template_tag_fp_lat_1800_d, 'LAT180_0507_160722_104023_00.csv')
```


Model LTD 1000/1100/1250
```{r}
list.files(template_tag_d_ltd_1000_1100_1250)
fp_psi = file.path(template_tag_d_ltd_1000_1100_1250, "3315PRESSURE.CSV")
fp_temp = file.path(template_tag_d_ltd_1000_1100_1250, "3315TEMPERATURE.CSV")
fp_xtemp = file.path(template_tag_d_ltd_1000_1100_1250, "3315XTEMPERATURE.CSV")


lt1000_dm = 
  DataMap_Lotek.1000.1100.1250(
    d = template_tag_d_ltd_1000_1100_1250,
    input_data_field_map = LOTEK_1000.1100.1250_FIELDS,
    output_data_field_map = TAG_DATA_FIELDS
  )

lt1000_dat = 
  lt1000_dm$extract()

lt1000_dm$transform(lt1000_dat)

dc = 
  Decoder_Lotek.1000.1100.1250(
    d = template_tag_d_ltd_1000_1100_1250
  )

dat = 
  dc$decode_datamap(dm = dc$data_maps[[1]])

dc$transform(d__, output_data_field_map = TAG_DATA_FIELDS, tag_meta_field_map = TAG_FIELDS)

dc$tag_id_from_d(template_tag_d_ltd_1000_1100_1250)



d__$generate_tag_meta_dataframe(tag_meta_field_map)
```

```{r}
dc = 
  Decoder_Lotek.1000.1100.1250(
    d = template_tag_d_ltd_1000_1100_1250,
    tag_meta_field_map = TAG_FIELDS
  )

dm = dc$data_maps[[1]]


Filter(
  Negate(is.null), 
  dm$output_data_field_map$field_list[
    c('TAG_ID_FIELD', 'TAG_MAKE_FIELD', 'TAG_MODEL_FIELD')
  ]
)

TAG_FIELDS$common_fields(dm$output_data_field_map)

dc$generate_tag_meta_dataframe(TAG_FIELDS)
```


Model LAT 1400/1800 
```{r}
# Tag ID
template_tag_fp_lat_1400_d
dir.exists(template_tag_fp_lat_1400_d)


tag_id_from_filename =
  function(fp) {
    stringr::str_match(fp, pattern = ".*\\D(\\d\\d\\d\\d)\\D.*")[2]
  }

tag_id_from_dir = 
  function(d) {
    tag_id_from_filename(
      list.files(
        d, 
        pattern = "^LAT[180|140].*csv"
      )[[1]]
    )
  }

tag_id_from_dir(template_tag_fp_lat_1400_d)

stringr::str_match(template_tag_fp_lat_1400_fp, pattern = ".*\\D(\\d\\d\\d\\d)\\D.*")[2]
str_match(template_tag_fp_lat_1800_fp, pattern = ".*\\D(\\d\\d\\d\\d)\\D.*")[2]
str_match(template_tag_fp_lat_1400_fp, pattern = ".*LAT(140|180).*")[2]
str_match(template_tag_fp_lat_1800_fp, pattern = ".*LAT(140|180).*")[2]


# Data extraction
d = template_tag_d_lat_1400_1800
d = template_tag_d_lat_1400_1800.2
d = template_tag_d_lat_1400_1800.3

length(Decoder_Lotek.1400.1800()$get_csv_files(d))


fp = file.path(d, list.files(d, pattern = "\\.[C|c][S|s][V|v]$"))[[1]]
data = read.csv(template_tag_fp_lat_1400_1800, skip = 2, nrows = 100)


dc = 
  Decoder_Lotek.1400.1800(
    d = template_tag_fp_lat_1400_d,
    tag_make = "Lotek",
    tag_model = "LAT_1400",
    input_data_field_map = LOTEK_1400.1800_FIELDS
  )

d__ = dc$extract()

output_data_field_map = TAG_DATA_FIELDS

dc$transform(
  d__,
  output_data_field_map = TAG_DATA_FIELDS,
  tag_meta_field_map = TAG_FIELDS
)


dc$transform

```

```{r}
input_data_field_map$field_list[names(input_data_field_map$field_list) %in% names(fm$field_list)]


input_data_field_map$common_fields(fm = output_data_field_map)
```


```{r}

dat__ = d__
.self = dc

transform_fields =
          function(dat__, output_data_field_map) {
            # Convert the datetime field(s) to a POSIXct field
            dat__ = .self$convert_datetime_to_posix_ct(dat__)

            # Process each input field in turn
            # Limit conversion to those fields shared by both the input data field
            #   map and the output data field map
            for (
              field_ in 
              names(
                .self$input_data_field_map$common_fields(
                  fm = output_data_field_map
                )
              )
            ) {
            # for (field_ in names(.self$input_data_field_map$field_list)) {
              # Identify relevant input/output field objects
              input_field_obj_ = .self$input_data_field_map$field_list[[field_]]
              output_field_obj_ = output_data_field_map$field_list[[field_]]

              # Isolate field data
              input_field_dat_ = dat__[[input_field_obj_$name]]

              # Make consideration for units
              if(!identical(output_field_obj_$units, character(0))) {
                # If units are specified on the output field, define and convert units
                input_field_dat_ =
                  units::set_units(
                    # Set initial units based on input field
                    units::set_units(
                      input_field_dat_,
                      input_field_obj_$units,
                      mode="standard"
                    ),
                    # Immediately convert units based on output field
                    output_field_obj_$units,
                    mode="standard"
                  )
              }

              # Re-append data to original object, with new name and (if applicable) units
              dat__[output_field_obj_$name] = input_field_dat_
            }

            return(
              dat__[
                lapply(
                  # Select the fields from the output field map that have corresponding
                  #  entries in the input field map
                  output_data_field_map$field_list[names(input_data_field_map$field_list)],
                  function(f) {
                    f$name
                  }
                ) %>%
                  unlist(use.names = F)
              ]
            )
          }
```


```{r}
output_data_field_map$common_fields(input_data_field_map)


.self$field_list[names(input_data_field_map$field_list)]
```



Model LTD 1300
```{r}
d = template_tag_d_lat_1300

fps = list.files(d, pattern = "Regular Log")
# CHECK ONE AND ONLY ONE FILE
fp = file.path(d, fps[[1]])

read.csv(fp)

length(fps)

dc_1300 = 
  Decoder_Lotek.1300(
    d = template_tag_d_lat_1300,
    tag_make = "Lotek",
    tag_model = "LAT_1300",
    input_data_field_map = LOTEK_1300_FIELDS
  )


dat_1300__ = dc_1300$extract()

dat_1300_t__ = 
  dc_1300$transform(
    dat_1300__,
    output_data_field_map = TAG_DATA_FIELDS,
    tag_meta_field_map = TAG_FIELDS
  )

dat_1300_t__ %>% 
  drop_na()
```



```{r}
fp = list.files(
  template_tag_d_ltd_1000_1100_1250,
  pattern = "^.*[C|c][S|s][V|v]"
)[[1]]



stringr::str_match(fp, pattern = "^(\\d\\d\\d\\d)\\D*")[2]
```


```{r}
.self = dc
dat__ = d__
output_data_field_map = TAG_DATA_FIELDS

transform_fields =
  function(dat__, output_data_field_map) {
    # Convert the datetime field(s) to a POSIXct field
    dat__ = .self$convert_datetime_to_posix_ct(dat__)

    # Process each input field in turn
    # Limit conversion to those fields shared by both the input data field
    #   map and the output data field map
    common_fields = 
      names(
          .self$input_data_field_map$common_fields(
            fm = output_data_field_map
          )
        )
    
    for (field_ in common_fields) {
      # for (field_ in names(.self$input_data_field_map$field_list)) {
      # Identify relevant input/output field objects
      input_field_obj_ = .self$input_data_field_map$field_list[[field_]]
      output_field_obj_ = output_data_field_map$field_list[[field_]]

      # Isolate field data
      input_field_dat_ = dat__[[input_field_obj_$name]]

      # Make consideration for units
      if(!identical(output_field_obj_$units, character(0))) {
        # If units are specified on the output field, define and convert units
        input_field_dat_ =
          units::set_units(
            # Set initial units based on input field
            units::set_units(
              input_field_dat_,
              input_field_obj_$units,
              mode="standard"
            ),
            # Immediately convert units based on output field
            output_field_obj_$units,
            mode="standard"
          )
      }

      # Re-append data to original object, with new name and (if applicable) units
      dat__[output_field_obj_$name] = input_field_dat_
    }

    return(
      dat__[
        lapply(
          # Select the fields from the output field map that have corresponding
          #  entries in the input field map
          output_data_field_map$field_list[common_fields],
          function(f) {
            f$name
          }
        ) %>%
        unlist(use.names = F)
      ]
    )
  }
```



```{r}
dl = Decoder_Lotek.1000.1100.1250()
class(dl)


list.files(template_tag_d_ltd_1000_1100_1250, pattern = ".*[C|c][S|s][V|v]")

df_psi = dl$read_csv_lotek_1000.1100.1250(fp_psi)
df_temp = dl$read_csv_lotek_1000.1100.1250(fp_temp)
df_xtemp = dl$read_csv_lotek_1000.1100.1250(fp_xtemp)

full_join(
  df_psi,
  df_temp
)

purrr::reduce(
  .x = 
    list(
      df_psi,
      df_temp,
      df_xtemp
    ),
  .f = 
    function(x, y) {
      # Check that the next df has any rows to join
      if (nrow(y) > 0) {
        return(
          full_join(x, y)
        )
      }
      return(x)
    }
)

d = template_tag_d_ltd_1000_1100_1250

c(
  "PRESSURE",
  "TEMPERATURE",
  "LIGHT",
  "SUPPLY"
) %>% 
  lapply(
    FUN = 
      function(pattern) {
        dl$read_csv_lotek_1000.1100.1250(
          dl$get_data_file_path(d, pattern = pattern)
        )
      }
  ) %>% 
  purrr::reduce(
  .f = 
    function(x, y) {
      # Check that the next df has any rows to join
      if (nrow(y) > 0) {
        return(
          full_join(x, y)
        )
      }
      return(x)
    }
)





d__$transform()
```


```{r}
d__ = dat_1000.1100.1250[1:100,]

d__ %>% 
  # Set appropriate input datatypes and units
  dplyr::mutate(
    "{OUTPUT_DATA_FIELDS['DATETIME_FIELD_NAME']}" := as.POSIXct(Time, format = "%Y/%m/%d %H:%M:%S")
    # "{PRESSURE_FIELD_NAME}" := units::set_units(units::as_units(Pressure.PSI, 'psi'), PRESSURE_FIELD_UNITS, mode = "standard"),
    # "{TEMPERATURE_FIELD_NAME}" := units::set_units(units::as_units(Temperature.C, '°C'), TEMPERATURE_FIELD_UNITS, mode = "standard")
  )


 
  dplyr::select(
    {{DATETIME_FIELD_NAME}},
    {{PRESSURE_FIELD_NAME}},
    {{TEMPERATURE_FIELD_NAME}}
  )
  
  d__ %>%
    



d__[[LOTEK_1000.1100.1250[['PRESSURE_FIELD_NAME']]]]

sym()

d__ %>% 
  dplyr::select(
    "{PRESSURE_FIELD_NAME}" := matches(LOTEK_1000.1100.1250[['PRESSURE_FIELD_NAME']])
  )

field_map = LOTEK_1000.1100.1250

field_map %>% 
  names %>% 
  reduce(
    .init = 
      d__,
    .f = 
      function(d_, n) {
        print(n)
        return(
          d_ %>% 
          dplyr::rename(
            "{OUTPUT_DATA_FIELDS[[n]]}" := sym(field_map[[n]])
          )
        )
      }
  )


```

```{r}
INPUT_FIELDS = LOTEK_1000.1100.1250_FIELDS

INPUT_FIELDS %>% 
  names %>% 
  # Go through the configured fields one by one
  # Rename them to the output field names, and (unless designated) convert
  # their units to the output field units
  reduce(
    .init = d__,
    .f = 
      function(d, n) {
        # First, rename the fields to the corresponding output field names
        d = 
          d %>% 
          dplyr::rename(
            '{TAG_DATA_FIELDS[[n]]$name}' := sym(INPUT_FIELDS[[n]]$name)
          )
        
        # Check to see if the field is designated for unit conversion
        if (TAG_DATA_FIELDS[[n]]$convert) {
          d %>% 
          dplyr::mutate(
          .,
          '{TAG_DATA_FIELDS[[n]]$name}' := 
            units::set_units(
              .[[TAG_DATA_FIELDS[[n]]$name]],
              INPUT_FIELDS[[n]]$units,
              mode = 'standard'
            )
          )
        }
        
        return(d)
      }
  )




```
































