```{r}
library(tidyverse)

mt_d = here::here('data', 'Microwave Telemetry', 'X-Tag')

mt_template_d = file.path(mt_d, 'Rougheye Rockfish', '118375')
```


```{r}
d = mt_template_d

mt_dc__ = 
  Decoder_MicrowaveTelemetry_XTag(d = d)

mt_dc__$decode(con)

MicrowaveTelemetry_XTag_TagMetaData()$extract(d)

mt_dm__ = mt_dc__$data_maps[[1]]

mt_dm__$input_data_field_map
```

```{r}
fs = list.files(.self$d, pattern = "\\.txt$", full.names = T)

fs %>% 
  lapply(
    function(fp) {
      read.csv(fp, sep = "\t")
    }
  )
```



```{r}
fs = list.files(.self$d, pattern = "^\\d*p\\.txt", full.names = T)

if (length(fs) > 1) {
  stop(paste0("Input File Error - Too many input files match template in directory ", .self$d))
}

mt_dat_ = 
  read.csv(
    fs,
    header = F,
    col.names = c("datetime", "pressure", "gain"),
    sep = '\t'
  )

mt_dat_ %>% 
  ggplot(aes(pressure)) + 
  geom_histogram()


pressure = read.csv(fs, sep = '\t')$Press
```

Extract data from .xls file
```{r}
mt_xt_xl_fp = list.files(.self$d, pattern = "^\\d*\\.xls", full.names = T)

press_dat_ = 
  # Read the data from the pressure data sheet in the xls file
  readxl::read_xls(
    path = mt_xt_xl_fp,
    sheet = "Press Data",
    # Calculate the range of data to include
    range = 
      paste0(
        "A3:D",
        # Read in the full, unfiltered sheet to count the number of rows of data
        nrow(
          readxl::read_xls(
            path = mt_xt_xl_fp,
            sheet = "Press Data",
            skip=1
          )
        ) + 2 # Add two rows for the header row and the title row
      ),
    col_names = 
      c(
        'datetime',
        'sensor_val',
        'gain',
        'depth'
      )
  ) %>% 
  dplyr::mutate(
    depth = units::set_units(-1 * depth, 'm')
  )


temp_dat_ = 
  # Read the data from the temperature data sheet in the xls file
  readxl::read_xls(
    path = mt_xt_xl_fp,
    sheet = "Temp Data",
    # Calculate the range of data to include
    range = 
      paste0(
        "A3:C",
        # Read in the full, unfiltered sheet to count the number of rows of data
        nrow(
          readxl::read_xls(
            path = mt_xt_xl_fp,
            sheet = "Temp Data",
            skip=1
          )
        ) + 2 # Add two rows for the header row and the title row
      ),
    col_names = 
      c(
        'datetime',
        'sensor_val',
        'temperature'
      )
  ) %>% 
  dplyr::mutate(
    temperature = units::set_units(temperature, '°C')
  )


dat_ = 
  merge(
    dplyr::select(press_dat_, -sensor_val, -gain),
    dplyr::select(temp_dat_, -sensor_val),
    all.x = T,
    all.y = T
  )
```

Identify tag_id from directory
```{r}
list.files(path = mt_template_d, pattern = "^\\d*\\.xls") %>% 
  stringr::str_extract(pattern = "^(\\d*)\\.xls", group=1)
```


```{r}
#' Datamap for the Microwave Telemetry X-tag tags
#'
#' @inheritParams Decoder
#'
#' @examples
DataMap_MicrowaveTelemetry_XTag_InstantSensorData =
  setRefClass(
    "DataMap_MicrowaveTelemetry_XTag_InstantSensorData",
    contains = "DataMap_InstantSensorData_Base",
    methods =
      list(
        initialize =
          function(...) {
            callSuper(input_data_field_map = MICROWAVE_TELEMETRY_XTAG_FIELDS, ...)
          },
        
        # Calculate the cell range string the desired data is in
        calc_range = 
          function(fp, sheet, col_range) {
            row_max = 
              # Read in the full, unfiltered sheet to count the number of rows of data in the file
              nrow(
                readxl::read_xls(
                  path = fp,
                  sheet = sheet,
                  skip=1
                )
              ) + 2 # Add one row for the title row
            
            return(
              paste0(
                col_range[[1]], 
                '2', 
                ':', 
                col_range[[2]], 
                row_max
              ) 
            )
          },
        
        # Helper function to extract data from excel sheet
        read_data_sheet = 
          function(fp, sheet, col_range) {
            suppressMessages(
              {
                return(
                  # Read the data from the pressure data sheet in the xls file
                  readxl::read_xls(
                    path = fp,
                    sheet = sheet,
                    # Calculate the range of data to include
                    range =
                      .self$calc_range(
                        fp, sheet, col_range
                      ),
                    col_names = T
                  )
                )
              }
            )
          }, 
            
        #' Extract tag data from passed directory
        #'
        #' @param d The directory in which the tag data resides. Directory is
        #' expected to contain only files which relate to one common tag.
        #'
        #' @return The data contained in the tag data as a single dataframe
        extract =
          function(d) {
            # All of the temperature and pressure data is extracted from the .xls file
            # Find the xls file in the directory
            mt_xt_xl_fp = list.files(d, pattern = "^\\d*\\.xls", full.names = T)

            press_dat = 
              .self$read_data_sheet(
                fp = mt_xt_xl_fp,
                sheet = "Press Data",
                col_range = c("A", "G")
              )
            
            temp_dat = 
              .self$read_data_sheet(
                fp = mt_xt_xl_fp,
                sheet = "Temp Data",
                col_range = c("A", "F")
              )
            
            dat =
              merge(
                press_dat,
                temp_dat,
                # join by the timestamp field
                by = .self$input_data_field_map$field_list$TIMESTAMP_FIELD$name,
                # Keep all records, even if they do not join
                all.x = T,
                all.y = T
              )
            
            # Convert each of the flag fields to bit flags
            for (
              field 
              in 
              c(
                .self$input_data_field_map$field_list$DEPTH_INCREASE_LIMIT_EXCEEDED_FIELD$name,
                .self$input_data_field_map$field_list$DEPTH_DECREASE_LIMIT_EXCEEDED_FIELD$name,
                .self$input_data_field_map$field_list$TEMPERATURE_INCREASE_LIMIT_EXCEEDED_FIELD$name,
                .self$input_data_field_map$field_list$TEMPERATURE_DECREASE_LIMIT_EXCEEDED_FIELD$name
              )
            ) {
              dat[field] = ifelse(!is.na(dat[[field]]), 1, dat[[field]])
            }

            return(dat)
          }
      )
  )


mt_xt_dm = 
  DataMap_MicrowaveTelemetry_XTag_InstantSensorData()

dat = mt_xt_dm$extract(d = mt_template_d)
dat_t = mt_xt_dm$transform(dat)

mt_xt_dc = 
  Decoder_MicrowaveTelemetry_XTag(d = mt_template_d)

mt_xt_dc$decode(con)
```

```{r}
col_range = c("A", "E")

calc_range = 
  function(fp, sheet, col_range) {
    row_max = 
      # Read in the full, unfiltered sheet to count the number of rows of data in the file
      nrow(
        readxl::read_xls(
          path = fp,
          sheet = sheet,
          skip=1
        )
      ) + 2 # Add one row for the title row
    
    return(
      paste0(
        col_range[[1]], 
        '2', 
        ':', 
        col_range[[2]], 
        row_max
      ) 
    )
  }

  
```

```{r}
# Read in sheet data
fp = mt_xt_xl_fp
sheet = "Press Data"
cell_range = "A2:E"

suppressMessages(
  {
    press_dat_ =
      # Read the data from the pressure data sheet in the xls file
      readxl::read_xls(
        path = fp,
        sheet = sheet,
        # Calculate the range of data to include
        range =
          paste0(
            cell_range,
            # Read in the full, unfiltered sheet to count the number of rows of data
            nrow(
              readxl::read_xls(
                path = fp,
                sheet = sheet,
                skip=1
              )
            ) + 2 # Add one row for the title row
          ),
        col_names = T
      )
  }
)

press_dat_
```





















