```{r}
so_d = here::here('data', 'Star Oddi')
so_dst_d = file.path(so_d, 'DST', 'Sablefish', 'JS7977')
so_dstmag_d = file.path(so_d, 'DST magnetic', 'Sablefish', 'JS927')
so_dstmf_d = file.path(so_d, 'DST milli-F', 'Sablefish', 'JS122')
```


```{r}
d = file.path(so_d, "DST magnetic", "Sablefish", "JS923")
d = file.path(so_d, "DST milli-F", "Sablefish", "JS108")


fs = list.files(d, pattern = "^[^~]*\\.xlsx", full.names = T)

fp = list.files(d, full.names = T, pattern = "^JS\\d\\d\\d\\.xlsx$")

TagIdentifier()$identify_tag_decoder(d)


fp = list.files(d, full.names = T)[[2]]

dm_ = DataMap_StarOddi_DSTmagnetic_InstantSensorData()
dm_ = DataMap_StarOddi_DST_InstantSensorData()

id_ = 
  .self = 
  Identifier_StarOddi_DST()

Identifier_StarOddi_DST()$identify(d)
Identifier_StarOddi_DSTmagnetic()$identify(d)


dat = 
  dm_$extract(d)

dat_t = 
  dm_$transform(dat)


dm_$input_data_field_map$field_list$TEMPERATURE_FIELD

readxl::read_xlsx(fp, sheet = "DAT", n_max = 1)

suppressMessages(
  class
)
```

```{r}
dat2 = 
  readxl::read_xlsx(
  fp,
  sheet = "DAT"
)

data.frame(
  dat2 = dat2$`Date & Time`,
  dat1 = dat$`Date & Time`
) %>% 
  dplyr::mutate(
    date = as.POSIXct(as.Date(dat2, origin = "1899-12-30"))
  )

as.POSIXct()



lubridate::hour(date__)
```































