#' Decoder base class
#'
#' Logical representation of a single tag, which contains all necessary logic to parse and extract all required data from an appropriately formatted directory. Contains one or more [DataMap] objects, each of which the Decoder will apply in turn to the directory in order to extract the necessary data. Contains an [Identifier] object, which can be used to automatically determine if a given directory contains the data generated by a tag of the make/model to which this Decoder refers.
#'
#' @field data_maps list. The list of data maps used to map the data for this tag to the output tables in the DB
#'
#' @export Decoder
Decoder =
  #----
setRefClass(
  "Decoder",
  fields =
    list(
      label = "character",
      identifier = "Identifier",
      data_maps = "list"
    ),

  methods =
    list(
      # Helper function to throw an error with a pre-appended message to help identify
      # the source of the error
      throw_error =
        function(msg) {
          stop(
            paste0(
              "ERROR - ",
              class(.self)[[1]],
              ": ",
              msg
            )
          )
        },

      # Execute all necessary steps to read and transform raw data for one DataMap
      decode_datamap =
        function(d, dm, op_fm) {
          "Execute all necessary steps to read and transform raw data for one DataMap"
          # Perform initial extraction
          dat_e =
            dm$extract(d)

          # Transform extracted data
          dat_et =
            dm$transform(dat_e, op_fm)

          # Augment transformed data
          dat_eta =
            dm$augment(dat_et, op_fm)

          # Return transformed data
          return(dat_eta)
        }
    )
)
